### ISSUE TITLE
Supplying a host with no port

### ISSUE THREAD

**Issue by ambival3nt** [CodeWithKyrian/chromadb-php#1]
When using this package with homestead, I need to use a tunnel to connect to chroma, which does not need a port supplied when given as host. Since the config is not publishable, this required modifying the library's code to accept a "$noPort" boolean to allow it.

Thought I'd let you know. Maybe having a publishable config would be your best bet?

Otherwise the package has worked quite well.

**Comment by CodeWithKyrian** [comment]
Thanks for bringing this to my attention. I'm considering making the port nullable, allowing one to use a method like withPort(null). Another option could be using withoutPort(), but that might introduce confusion in the future, as users could inadvertently call both methods.

**Comment by CodeWithKyrian** [comment]
On a second thought, did you try using port 80?

**Comment by ambival3nt** [comment]
> Thanks for bringing this to my attention. I'm considering making the port nullable, allowing one to use a method like withPort(null). Another option could be using withoutPort(), but that might introduce confusion in the future, as users could inadvertently call both methods.

I just added a flag to the argument list, a bool. it's a rare case but because of my homestead instance and needing to tunnel to chroma it had to change (windows user)

**Comment by ambival3nt** [comment]
> On a second thought, did you try using port 80?

wouldn't that still require my changing it
