### ISSUE TITLE
OpenAIEmbeddingFunction

### ISSUE THREAD

**Issue by EliasPereirah** [CodeWithKyrian/chromadb-php#6]
Fatal error: Uncaught Error: Class "OpenAIEmbeddingFunction" not found in...
What could be?

**Comment by CodeWithKyrian** [comment]
Could you share more information about the error? The full error message and the script you encountered the error so I can ascertain where the problem could be from?

**Comment by EliasPereirah** [comment]
> Could you share more information about the error? The full error message and the script you encountered the error so I can ascertain where the problem could be from?

**The error:** Fatal error: Uncaught Error: Class "OpenAIEmbeddingFunction" not found in /var/www/html/Chroma/index.php:14 Stack trace: #0 {main} thrown in /var/www/html/Chroma/index.php on line 14

This occurs when I try to use this code:
```

use CodeWithKyrian\ChromaDB\EmbeddingFunction\EmbeddingFunctionInterface;

$embeddingFunction = new OpenAIEmbeddingFunction('api-key', 'org-id', 'model-name');
```

**Comment by CodeWithKyrian** [comment]
Import the `vendor/autoload.php` file at the top of your index.php to be able to import the class

**Comment by EliasPereirah** [comment]
> Import the `vendor/autoload.php` file at the top of your index.php to be able to import the class

Sorry, I only included the part that I thought was necessary, but I imported autoload before, it even works for chat, but not for embedding.
